// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWebPositionApp.Data;

#nullable disable

namespace SimpleWebPositionApp.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20221130170659_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("SimpleWebPositionApp.Models.CodeItem", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("TopCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Barcode");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("SimpleWebPositionApp.Models.Login", b =>
                {
                    b.Property<int>("Login_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Login_id");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("SimpleWebPositionApp.Models.ProductItem", b =>
                {
                    b.Property<string>("TopCode")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance68")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceCentral")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CapacityCentral")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monthly")
                        .HasColumnType("TEXT");

                    b.Property<string>("Position68")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionCentral")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Reserved68")
                        .HasColumnType("TEXT");

                    b.Property<int>("TransactionLine")
                        .HasColumnType("INTEGER");

                    b.HasKey("TopCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SimpleWebPositionApp.Models.SearchBar", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("SearchBar");
                });
#pragma warning restore 612, 618
        }
    }
}
